import os
import json
import pytest
from src.ingestion.pdf_parser import parse_pdf
from src.ingestion.scraper import scrape_url
from src.ingestion.chunker import chunk_text
from src.ingestion.diff_detector import detect_changes


def test_pdf_parsing():
    """Verify that PDF parsing extracts meaningful text from raw PDFs."""
    raw_dir = "data/raw"
    assert os.path.exists(raw_dir), "data/raw directory does not exist"
    
    pdf_files = [f for f in os.listdir(raw_dir) if f.endswith(".pdf")]
    assert len(pdf_files) > 0, "No raw PDF files found in data/raw for testing"

    for pdf_file in pdf_files[:3]:
        text = parse_pdf(os.path.join(raw_dir, pdf_file), max_pages=2)
        assert len(text) > 100, f"Extracted text too short: {pdf_file}"
        # Factsheets and booklets should contain basic mutual fund vocabulary
        vocabulary_check = any(
            word in text.lower() 
            for word in ["expense", "ratio", "nav", "fund", "scheme", "holding", "portfolio", "hdfc"]
        )
        assert vocabulary_check, f"PDF text lacks expected mutual fund contents: {pdf_file}"


def test_html_scraping():
    """Verify that HTML scraping extracts raw text from web URLs."""
    sources_path = "data/sources.json"
    assert os.path.exists(sources_path), "data/sources.json does not exist"
    
    with open(sources_path) as f:
        sources = json.load(f)

    html_sources = [s for s in sources if s.get("format") == "html"]
    assert len(html_sources) > 0, "No HTML sources found in sources.json"

    # Scraping a sample HTML page to verify it works (try until one succeeds to handle 404s/network issues)
    text = ""
    scraped_url = ""
    for src in html_sources:
        try:
            text = scrape_url(src["url"])
            if len(text) > 50:
                scraped_url = src["url"]
                break
        except Exception:
            continue

    assert len(text) > 50, f"Could not scrape any HTML source URL successfully. Tried: {[s['url'] for s in html_sources]}"
    assert "<script" not in text, "Scraped text contains script tags"
    assert "<nav" not in text, "Scraped text contains navigation tags"
    assert "<style" not in text, "Scraped text contains styling tags"


def test_chunking():
    """Verify that chunking splits documents recursively with correct metadata."""
    sample_text = """
    Scheme Name: HDFC Large Cap Fund
    Category: Large Cap Equity Fund
    Expense Ratio (Direct Plan): 0.82%
    Exit Load: 1% if redeemed within 1 year.
    Minimum SIP Amount: Rs. 500.
    Benchmark: NIFTY 100 TRI.
    
    The HDFC Large Cap Fund is a diversified equity scheme that primarily invests in large-cap stocks.
    The primary investment objective of the scheme is to generate long-term capital appreciation from a portfolio
    predominantly investing in equity and equity-related instruments of large-cap companies.
    """
    
    chunks = chunk_text(
        text=sample_text,
        source_url="https://www.hdfcfund.com/mutual-funds/factsheets",
        scheme_name="HDFC Large Cap Fund",
        source_type="factsheet",
        document_date="2026-04-30"
    )
    
    assert len(chunks) >= 1, "No chunks generated by chunker"
    
    for i, chunk in enumerate(chunks):
        assert 100 <= len(chunk["text"]) <= 1000, f"Chunk {i} size out of bounds: {len(chunk['text'])}"
        assert chunk["source_url"] == "https://www.hdfcfund.com/mutual-funds/factsheets"
        assert chunk["scheme_name"] == "HDFC Large Cap Fund"
        assert chunk["source_type"] == "factsheet"
        assert chunk["document_date"] == "2026-04-30"
        assert "chunk_id" in chunk
        assert "ingestion_date" in chunk


def test_diff_detection(tmp_path):
    """Verify that incremental diff detection correctly flags content changes."""
    # Create a temporary mock sources file
    mock_sources = [
        {"url": "local_source_1", "scheme": "Scheme A", "type": "factsheet", "format": "txt"},
        {"url": "local_source_2", "scheme": "Scheme B", "type": "faq", "format": "txt"},
        {"url": "local_source_3", "scheme": "Scheme C", "type": "kim", "format": "txt"}
    ]
    
    sources_path = os.path.join(tmp_path, "mock_sources.json")
    temp_cache_path = os.path.join(tmp_path, "temp_hashes.json")
    
    with open(sources_path, "w") as f:
        json.dump(mock_sources, f)
        
    try:
        # First run: should flag all sources as changed since cache is empty
        changes_1 = detect_changes(sources_path, temp_cache_path)
        assert len(changes_1) == len(mock_sources), "First run did not detect all sources as changed"
        assert os.path.exists(temp_cache_path), "Hashes cache file was not created"
        
        # Second run: should flag 0 sources since content is unchanged
        changes_2 = detect_changes(sources_path, temp_cache_path)
        assert len(changes_2) == 0, f"Second run flagged {len(changes_2)} changed sources (expected 0)"
        
    finally:
        pass
